---
# Разворачиваю nginx как балансировщик нагрузки

- name: Stop and remove existing Nginx container if it exists
  docker_container:
    name: "{{ nginx_container_name }}"
    state: absent
  ignore_errors: true

- name: Create Nginx configuration directory
  file:
    path: /opt/nginx/conf
    state: directory
    mode: '0755'

- name: Generate Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /opt/nginx/conf/nginx.conf
    mode: '0644'

- name: Pull the Nginx image
  docker_image:
    name: nginx:latest
    source: pull

- name: Run Nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: nginx:latest
    state: started
    restart_policy: always
    platform: linux/amd64
    networks:
      - name: echo_network
    published_ports:
      - "{{ nginx_host_port }}:{{ nginx_container_port }}"
    volumes:
      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    recreate: true 