---

- name: Setup Echo Server Environment
  hosts: echo_servers
  become: true
  roles:
    - role: docker
      tags: [docker]
    - role: app
      tags: [app]
    - role: nginx
      tags: [nginx]